# Site
repository: aatishraj/aatishraj.github.io
favicon: images/favicon.ico

# Personal info
name: Aatishraj Kalawade
title: Senior (SRE) Software Engineer
email: aatishraj@gmail.com
# website: https://aatishraj.github.io

# Social links
# twitter_username: facespics
# github_username:  aatishraj
# dribbble_username: jekyll
# facebook_username: aatishraj
# flickr_username: jekyll
# instagram_username: aatishraj
linkedin_username: akalawade
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# Additional icon links
# additional_links:
# - title: Resume link
#   icon: fa-git-square
#   url: https://github.com/aatishraj/aatishraj.github.io/blob/master/doc/Aatish_Resume.pdf

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Software Engineer at NVIDIA with 10+ years building and operating large-scale infrastructure and automation.

  Experienced across SRE/DevOps and platform engineeringâ€”reliability engineering, incident response, distributed systems operations, and CI/CD-driven automation.

  I focus on reducing operational toil, improving availability, and shipping pragmatic tooling that scales across regions and teams.

  Born and raised in Mumbai, where I completed my schooling and undergraduate degree, after which I moved to the United States in 2009 to pursue my graduate degree in Computer Science.

  My passion lies in providing the best Customer Support Experience possible. I have worked with a range of different languages and  technology stacks and I am always looking for opportunities to work on something new.

# Projects Section
projects_title: Work Experience

# Experience Section
experience_title: Technical Skills

# Education Section
# educaton_title: Education

# More Section
more_title: When I'm Not Programming
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in DevOps and Software Engineering some of my other interests & hobbies are: 
    - Playing Guitar
    - Photography
    - Singing
    - Hiking

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

theme: jekyll-theme-cayman
